Customise mobile nav
jpmorganchase/salt-ds pull request #1333
Opened 2023-03-21 10:24 UTC by JoanaMMoreira

2023-03-21 22:51 UTC, joshwooding requested changes

2023-03-21 22:51 UTC, joshwooding commented on mosaic-site/docs/index.mdx
> +      - title: Github
```suggestion
      - title: GitHub
```

2023-03-23 09:51 UTC, Fercas123 approved these changes

2023-03-23 11:32 UTC, joshwooding approved these changes

2023-03-23 11:32 UTC, james-nash approved these changes
👍

2023-03-23 13:26 UTC, merged