Avatar ADA changes
jpmorganchase/salt-ds pull request #1362
Opened 2023-03-23 16:14 UTC by Fercas123

- add aria labels to default icon and alternative icon example
- wrap initials in role image with aria label
- add accessibility recommendations to docs

2023-03-23 16:29 UTC, ZarkoPernar approved these changes

2023-03-24 11:26 UTC, joshwooding requested changes

2023-03-24 11:26 UTC, joshwooding commented on packages/core/src/avatar/Avatar.tsx
> +  const avatarInitials = nameToInitials(name) && (
I feel like this short-circuiting makes the code hard to read. If this was split out it would be easier to follow the logic.

2023-03-24 11:26 UTC, joshwooding commented on packages/core/src/avatar/Avatar.tsx
Is it worth applying aria-labels to all the individual fallback mechanisms? What is the downside of applying it to the root of the avatar and making everything inside presentational?

2023-03-24 13:20 UTC, Fercas123 commented on packages/core/stories/avatar/avatar.doc.stories.mdx
> +If an alternative icon is used inside an avatar, the icon's `aria-label` should be descriptive in relation to the avatar context, not the icon context. For example, when using `<BuildingSolidIcon/>`
@rufcha can I please ask for a review in this new paragraph for avatar's documentation?

2023-03-28 16:09 UTC, joshwooding approved these changes

2023-03-29 12:11 UTC, merged