Countries
jpmorganchase/salt-ds pull request #1410
Opened 2023-03-30 14:06 UTC by el-dav

2023-03-30 15:37 UTC, el-dav commented
Moved this to a new PR to see if chromatic build would work and cleaned up commits

2023-03-31 08:45 UTC, Fercas123 approved these changes

2023-03-31 09:01 UTC, joshwooding requested changes
Some minor changes needed on docs structure

2023-03-31 10:48 UTC, Fercas123 commented on packages/countries/stories/country-symbol.doc.stories.mdx
> +## Size
```suggestion
## Features

### Size
```

2023-03-31 10:48 UTC, Fercas123 commented on packages/countries/stories/country-symbol.doc.stories.mdx
> +## Usage
```suggestion
### Usage
```

2023-03-31 10:48 UTC, Fercas123 commented on packages/countries/stories/country-symbol.doc.stories.mdx
> +## Metadata
```suggestion
### Metadata
```

2023-03-31 13:13 UTC, joshwooding requested changes

2023-03-31 13:13 UTC, joshwooding commented on .changeset/rotten-guests-sort.md
> +<LazyCountrySymbol size={1} code={AD} />
```suggestion
<LazyCountrySymbol size={1} code="AD" />
```

2023-03-31 15:10 UTC, joshwooding commented
/release-pr

2023-03-31 16:49 UTC, joshwooding commented
/release-pr

2023-04-03 10:59 UTC, joshwooding commented
/release-pr

2023-04-03 13:29 UTC, joshwooding commented
/release-pr

2023-04-03 13:32 UTC, joshwooding commented
/release-pr

2023-04-05 09:23 UTC, joshwooding commented
/release-pr

2023-04-05 10:53 UTC, merged