Banner design changes
jpmorganchase/salt-ds pull request #1634
Opened 2023-05-10 08:46 UTC by alycrys

2023-05-17 13:55 UTC, libertymayc commented
lgtm, changeset? :)

2023-05-17 13:59 UTC, Fercas123 approved these changes
LGTM

2023-05-17 14:14 UTC, libertymayc submitted a review, later dismissed

2023-05-17 14:44 UTC, joshwooding requested changes

2023-05-17 14:44 UTC, joshwooding commented on .changeset/serious-parrots-speak.md
> +Banner style changes to use spacing foundation
```suggestion
Updated Banner to use the new spacing foundation
```

2023-05-17 14:45 UTC, joshwooding commented on packages/lab/src/banner/Banner.tsx
> +      <StatusIndicator status={status} className={clsx(withBaseName("icon"))} />
```suggestion
      <StatusIndicator status={status} className={withBaseName("icon")} />
```

2023-05-17 14:46 UTC, joshwooding commented on packages/lab/stories/banner/banner.stories.tsx
> +              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
We should be trying to avoid using lorem ipsum. Is there a better example text we can use here?

2023-05-18 10:56 UTC, joshwooding approved these changes

2023-05-18 14:01 UTC, merged