Fix for deprecated error prop
jpmorganchase/salt-ds pull request #1844
Opened 2023-06-16 14:37 UTC by libertymayc

Fix for deprecated error prop in CB and RB; still support styling for now
Accidentally removed in #1839 when adding validationStatus

2023-06-16 16:04 UTC, joshwooding requested changes

2023-06-16 16:04 UTC, joshwooding commented on .changeset/nice-roses-fail.md
> +Fix for deprecated `error` prop on Checkbox and RadioButton: ensures styling still works for deprecated prop.
I don't think we need a changeset. The deprecation hasn't been released yet

2023-06-16 16:04 UTC, joshwooding commented
Could you add the reason why this was needed to the PR please

2023-06-19 11:42 UTC, alycrys approved these changes

2023-06-20 21:42 UTC, merged