fix button in ag grid filter panel
jpmorganchase/salt-ds pull request #1875
Opened 2023-06-20 14:29 UTC by Fercas123

add `ag-standard-button` styles to salt-ag-theme

2023-06-20 16:46 UTC, origami-z commented
@pedroBlazquez can you help whether the buttons are aligned with what you have right now?

2023-06-21 09:11 UTC, joshwooding requested changes
Can you add a Changeset please

2023-06-23 12:11 UTC, joshwooding approved these changes

2023-06-23 12:11 UTC, joshwooding requested changes

2023-06-23 12:11 UTC, joshwooding commented on .changeset/short-shrimps-reflect.md
> +Add salt styles to `.ag-standard-button`.
Can you update the changeset to describe the issue that is being fixed please

2023-06-27 10:43 UTC, joshwooding submitted a review, later dismissed

2023-06-27 12:51 UTC, ZarkoPernar commented on packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
> +  .ag-standard-button {
I assume it doesn't have a focus ring?

2023-06-27 13:08 UTC, Fercas123 commented on packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
> +  .ag-standard-button {
nice catch, I'll add that in

2023-07-07 17:48 UTC, ZarkoPernar approved these changes

2023-07-10 09:12 UTC, origami-z approved these changes
Difference between UITK now is whether they're centered. Will leave to future alignment.

2023-07-10 09:39 UTC, merged