Change pronounced prop to intent in FormFieldLabel
jpmorganchase/salt-ds pull request #2007
Opened 2023-07-18 16:06 UTC by libertymayc

Discussed in dev call 18/7

2023-07-19 09:43 UTC, libertymayc commented on .changeset/fresh-planets-talk.md
> +Change `pronounced` prop to `intent` enum. Use "strong" for pronounced label styling
```suggestion
Change `pronounced` prop to `intent` enum. Use "sentence" for pronounced label styling
```

2023-07-19 09:45 UTC, libertymayc commented
discussed with Ben, decided 'label' and 'sentence' are suitable values for intent

2023-07-19 15:19 UTC, Fercas123 approved these changes

2023-07-19 17:24 UTC, ZarkoPernar approved these changes

2023-07-20 09:24 UTC, alycrys commented on .changeset/fresh-planets-talk.md
> +Change `pronounced` prop to `intent` enum. Use "sentence" for pronounced label styling
this sounds a bit confusing

2023-07-20 09:27 UTC, alycrys commented on packages/core/stories/form-field/form-field.doc.stories.mdx
> +The Form Field Label can be styled as a question by setting the `intent` prop to `sentence`.
```suggestion
The Form Field Label can be emphasized by setting the `intent` prop to `sentence`.
```

2023-07-20 09:33 UTC, libertymayc commented on .changeset/fresh-planets-talk.md
> +Change `pronounced` prop to `intent` enum. Use "sentence" for pronounced label styling
```suggestion
Removed `pronounced` prop to
Added `intent` prop. Use `intent` with "sentence" value to replace pronounced label styling
```

2023-07-20 09:45 UTC, libertymayc commented on .changeset/fresh-planets-talk.md
> +Change `pronounced` prop to `intent` enum. Use "sentence" for pronounced label styling
updated, lmk

2023-07-20 09:51 UTC, alycrys commented on .changeset/fresh-planets-talk.md
> +Removed `pronounced` prop to
```suggestion
Removed `pronounced` prop.
```

2023-07-20 10:32 UTC, joshwooding requested changes

2023-07-20 10:32 UTC, joshwooding commented on .changeset/fresh-planets-talk.md
> +Added `intent` prop. Use `intent` with "sentence" value to replace pronounced label styling
```suggestion
The `pronounced` prop has been replaced with the `intent` prop.

```diff
- <FormLabel pronounced />
+ <FormLabel intent="sentence" />
```

2023-07-20 14:02 UTC, joshwooding approved these changes

2023-07-20 17:10 UTC, ZarkoPernar approved these changes

2023-07-21 07:11 UTC, alycrys approved these changes

2023-07-21 08:39 UTC, merged