Checkbox and Radiobutton design fixes
jpmorganchase/salt-ds pull request #2039
Opened 2023-07-24 11:58 UTC by libertymayc

Minor fixes noticed by @pseys

2023-07-24 12:08 UTC, joshwooding requested changes
I believe this breaks the Checkbox alignment.

2023-07-24 14:31 UTC, joshwooding commented
> > I believe this breaks the Checkbox alignment.
> 
> how so?

Applying align-items to Checkbox means that when there is a long label the checkbox aligns to the centre rather than the baseline.

2023-07-24 22:12 UTC, joshwooding requested changes
What issue is this solving, can you raise a bug

2023-07-25 11:17 UTC, joshwooding commented on .changeset/soft-ligers-run.md
> +Fixed control size in RadioButton to match the shown icon size
```suggestion
Fixed control size in Radio Button to match the shown icon size.
```

2023-07-25 11:17 UTC, joshwooding approved these changes

2023-07-25 12:21 UTC, joshwooding approved these changes

2023-07-25 13:07 UTC, Fercas123 approved these changes

2023-07-25 13:13 UTC, merged