Update characteristics page
jpmorganchase/salt-ds pull request #2262
Opened 2023-08-18 11:11 UTC by mikearildbrown

Includes a round of edits from myself, @sion-docs and a third-party proofreading service.

2023-08-21 10:15 UTC, james-nash commented
FYI, just pushed a fix for the failing lint test.

2023-08-29 09:20 UTC, james-nash commented on site/docs/foundations/characteristics/index.mdx
> +For developers, they offer an easy way to reuse the same values. It creates a single point of reference for commonly used values, which means you only have to update in one place for it to reflect ev
Hmm... the first line about designers feels a bit woolly. What's it actually saying? It's not clear how visual changes without tokens impact the "efficiency or effectiveness of components".

As for the second point - that benefit also applies to designers.

The following bullet list summarises the benefits quite well IMHO, so perhaps these 2 paragraphs aren't needed at all?

That being said, one additional benefit I'd call out (perhaps as an additional bullet below?) is that (characteristic) design tokens create a shared language between designers, devs and other stakeholders - they all use the same names to refer to the same aspects/concepts in Salt-based UIs. That helps avoid miscommunications and streamlines design-to-dev handovers too.

2023-08-29 09:22 UTC, james-nash requested changes
Mostly looks good to me, but I think the "Benefits" section might need some tweaks.

2023-08-31 13:39 UTC, libertymayc commented on site/docs/foundations/characteristics/index.mdx
>  Characteristics offer the following benefits:
we got rid of bullets for below points, but added for the bullets below? @mikearildbrown

2023-08-31 13:42 UTC, libertymayc commented on site/docs/foundations/characteristics/index.mdx
> +- Streamlined design changes, e.g., a characteristic tweak automatically applying to all related components
```suggestion
- Single reference points for commonly used values
- Streamlined design changes, e.g., a characteristic tweak automatically applying to all related components
- Shared language enabling smooth handovers from design to development
```

2023-08-31 15:56 UTC, libertymayc commented on site/docs/foundations/characteristics/index.mdx
>  Characteristics offer the following benefits:
sorry, i meant we got rid of the full stops on these bullet points, but added them to the below ones

2023-09-01 14:16 UTC, libertymayc commented on site/docs/foundations/characteristics/index.mdx
>  Characteristics offer the following benefits:
below, bullet point full stops removed end of each sentence

- Ability to theme the Salt inline with third-parties or CIB sub brand guidelines.	- Ability to theme Salt in line with third parties or sub-brand guidelines
- Increase consistency across all components, with the knock-on effect of improving the overall user experience e.g. reduced cognitive load.	- Increased consistency across all components, improving the overall user experience, e.g., reduced cognitive load
- Simplified design of new components and patterns e.g. drag-and-drop behavior.	- Simplified design of new components and patterns e.g., drag-and-drop behavior
- Streamlined evolution – a single change to a characteristic will automatically cascade down through all related components within the library.	- Streamlined design changes, e.g., a characteristic tweak automatically applying to all related components

line ~36, full stops added
1. Always begin with `--salt-`.
2. Follow with the foundation name, e.g., `--salt-actionable-`, `--salt-text-`, `--salt-focused-`.
3. Append the variant if applicable, e.g., `--salt-actionable-cta-`, `--salt-text-h2-`.
4. Append the attribute, e.g., `--salt-actionable-cta-background`, `--salt-text-h2-fontSize`, `--salt-focused-outlineColor`.
5. Append the state if applicable, e.g., `--salt-actionable-cta-background-hover`.

2023-09-05 17:43 UTC, libertymayc commented
what's happening with this PR @mikearildbrown

2023-09-06 08:56 UTC, james-nash approved these changes
👍

2023-09-06 11:13 UTC, pseys commented
I'm taking a look at this now, but with interruptions its taking me time to get through it. I'll update with my feedback as soon as possible.

2023-09-11 19:19 UTC, merged