Replace browser incompatible props
jpmorganchase/salt-ds pull request #2342
Opened 2023-09-06 09:39 UTC by Fercas123

add missing prefix to appearance and revert inline and block margin/paddings to improve browser compatibility with Chrome 79

2023-09-06 13:29 UTC, feliciackh approved these changes

2023-09-06 13:35 UTC, libertymayc approved these changes

2023-09-06 13:38 UTC, JoanaMMoreira approved these changes

2023-09-06 14:13 UTC, joshwooding requested changes
This will need a changeset

2023-09-06 15:32 UTC, libertymayc approved these changes

2023-09-06 15:32 UTC, feliciackh submitted a review, later dismissed

2023-09-06 15:34 UTC, JoanaMMoreira approved these changes

2023-09-07 12:48 UTC, libertymayc approved these changes

2023-09-07 13:31 UTC, alycrys approved these changes

2023-09-07 14:01 UTC, merged