Fix FormField adds extra "padding" below the input
jpmorganchase/salt-ds pull request #2500
Opened 2023-09-25 16:31 UTC by libertymayc

closes #2497

ideally would use :has selector instead

2023-09-26 09:48 UTC, ZarkoPernar submitted a review, later dismissed

2023-09-26 09:52 UTC, joshwooding requested changes

2023-09-26 09:52 UTC, joshwooding commented on packages/core/stories/form-field/styles.css
Is this empty file intended?

2023-09-26 09:56 UTC, lilyvc submitted a review, later dismissed

2023-09-26 12:49 UTC, libertymayc commented on packages/core/stories/form-field/styles.css
oops! good spot i was testing something else

2023-09-26 15:21 UTC, lilyvc approved these changes

2023-09-27 16:32 UTC, ZarkoPernar approved these changes

2023-09-27 21:58 UTC, merged