remove repeated tokens & changeset from theme
jpmorganchase/salt-ds pull request #2613
Opened 2023-10-13 16:13 UTC by feliciackh

PR for Spinner and Progress introduced same foundations/size `--salt-size-bar-small` tokens, remove repeated reference of it

2023-10-13 16:19 UTC, origami-z requested changes
These are used in progress?

2023-10-13 16:20 UTC, origami-z approved these changes

2023-10-13 16:25 UTC, feliciackh commented
> These are used in progress?

Yeah used in both Spinner & Progress components, which was merged into main one after another so might have been overlooked

2023-10-14 17:09 UTC, origami-z commented
Updated release note (https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Ftheme%401.9.0), remove the code in next relevant PR

2023-10-14 17:09 UTC, closed without merging