Turn off prefer-nullish-coalescing
jpmorganchase/salt-ds pull request #2648
Opened 2023-10-26 08:25 UTC by origami-z

A lot of false negative between `??` and `||`

2023-10-26 13:30 UTC, Fercas123 submitted a review, later dismissed

2023-10-30 09:15 UTC, james-nash submitted a review, later dismissed

2023-10-30 09:46 UTC, joshwooding requested changes

2023-10-30 09:46 UTC, joshwooding commented on .eslintrc.js
> +        "@typescript-eslint/prefer-nullish-coalescing": "off",
```suggestion
    		"@typescript-eslint/prefer-nullish-coalescing": [
          		"error",
     		     {
    		        ignoreConditionalTests: true,
  		        },
```

Have you considered only turning of instances that have a high rate of false positives?

2023-10-30 09:58 UTC, joshwooding commented on .eslintrc.js
> +        "@typescript-eslint/prefer-nullish-coalescing": "off",
Actually a better option would be:

```suggestion
        "@typescript-eslint/prefer-nullish-coalescing": [
        "error",
        {
        	ignorePrimitives: { boolean: true }
        }],
```

2023-10-30 11:44 UTC, origami-z commented
Back to draft until i have time to look at this again

2023-11-07 12:17 UTC, closed without merging