fix combobox onchange lagging one render behind the input
jpmorganchase/salt-ds pull request #2697
Opened 2023-11-08 16:26 UTC by el-dav

Fix issue where combobox onChange was lagging behind the text typed into the combobox by one render. 

This was caused by sending inputValue to the onInputChange callback which had been set via setInputValue, but won't be updated till the next render.

Instead this change passes the value from event/target.value which will be the updated value.

2023-11-08 16:29 UTC, joshwooding requested changes
Could you add a changeset please

2023-11-09 16:54 UTC, origami-z approved these changes

2023-11-09 16:54 UTC, origami-z commented on .changeset/ninety-queens-retire.md
> +Fix combobox onchange using stale value
Probably need "next"

2023-11-09 17:17 UTC, joshwooding commented on .changeset/ninety-queens-retire.md
> +Fix combobox onchange using stale value
```suggestion
Fix Combo Box Next `onChange` using stale values
```

2023-11-09 17:51 UTC, el-dav commented on .changeset/ninety-queens-retire.md
> +Fix combobox onchange using stale value
Ah yes, thanks

2023-11-10 09:31 UTC, origami-z approved these changes

2023-11-10 09:37 UTC, joshwooding approved these changes

2023-11-10 16:01 UTC, merged