Remove override style for pinned column's border
jpmorganchase/salt-ds pull request #2756
Opened 2023-11-20 16:26 UTC by alycrys

closes https://github.com/jpmorganchase/salt-ds/issues/2755

2023-11-20 16:32 UTC, joshwooding commented on .changeset/chilly-cherries-build.md
> +Remove override style for pinned column's text
Can you put the reasoning behind this was done in the changeset please, as well as make the changeset past tense.

2023-11-20 16:32 UTC, joshwooding requested changes
Left a comment

2023-11-21 11:01 UTC, joshwooding commented on .changeset/chilly-cherries-build.md
> +Bug fix: The cell text from the pinned column was overlapping the cell next to it.
```suggestion
Cell text from a pinned column no longer overlaps the cell next to it.
```

2023-11-21 12:35 UTC, joshwooding approved these changes

2023-11-21 13:51 UTC, Fercas123 approved these changes

2023-11-21 13:52 UTC, merged