fixes
jpmorganchase/salt-ds pull request #2902
Opened 2024-01-11 11:46 UTC by alycrys

2024-01-16 11:05 UTC, joshwooding commented on packages/lab/src/navigation-item/NavigationItem.css
> +  --saltIcon-color: var(--salt-content-primary-foreground);
Do we really need to change the icon color?

2024-01-16 13:31 UTC, feliciackh submitted a review, later dismissed

2024-01-16 13:40 UTC, Fercas123 approved these changes

2024-01-16 15:13 UTC, joshwooding commented on packages/lab/src/navigation-item/NavigationItem.tsx
> +            withBaseName(),
I find it confusing that the root classname was moved. The style prop and the rest of the props appear on the root element?

2024-01-16 15:15 UTC, joshwooding requested changes
There's a bug when the Navigation Item is in active state the parent icon disappears

2024-01-16 15:16 UTC, joshwooding commented on packages/lab/src/navigation-item/ConditionalWrapper.tsx
>      <Button
I think we are better off refactoring this to not use Salt's Button directly. Dependencies like this cause issues with CSS specificity and make overrides confusing to consumers.

2024-01-17 12:45 UTC, alycrys commented
> There's a bug when the Navigation Item is in active state the parent icon disappears

Which icon? I'm not seeing it

2024-01-18 15:50 UTC, joshwooding commented
> > There's a bug when the Navigation Item is in active state the parent icon disappears
> 
> Which icon? I'm not seeing it

My suggestion to stop using `<Button>`\`<Link>` fixed this. The issue was probably around Button's active styles being applied to nav item.

2024-01-18 15:52 UTC, Fercas123 approved these changes

2024-01-19 10:58 UTC, merged