International Address Form pattern edits
jpmorganchase/salt-ds pull request #2975
Opened 2024-02-02 11:42 UTC by mikearildbrown

2024-02-02 11:50 UTC, joshwooding commented on site/docs/patterns/international-address-input.mdx
> +## Feedback
Is this going to be standard across all the pages? If so we should just create a component to template it.

2024-04-11 14:45 UTC, joshwooding commented on site/docs/patterns/international-address-input.mdx
>    - /salt/patterns/international-address-input
```suggestion
  - /salt/patterns/international-address-form
```

2024-04-12 06:59 UTC, joshwooding commented on site/docs/patterns/international-address-form.mdx
> +      src: "/img/patterns/international-address-input/iai-dynamic-format-toggle-off.png",
I think this image needs to be updated.

2024-04-12 06:59 UTC, joshwooding requested changes
See comment

2024-04-15 13:35 UTC, shey-v approved these changes

2024-04-16 13:59 UTC, shey-v approved these changes

2024-04-16 14:13 UTC, joshwooding approved these changes

2024-04-16 15:33 UTC, merged