Fix Tab deletion during editing
jpmorganchase/salt-ds pull request #3041
Opened 2024-02-22 18:35 UTC by stevenmckinnon

Fixing issue where Tab could be deleting whilst editing label and pressing backspace. 

Referenced in issue https://github.com/jpmorganchase/salt-ds/issues/3036

2024-02-23 16:24 UTC, origami-z approved these changes

2024-02-23 16:35 UTC, origami-z commented
May need to go through #3045 so Chromatic will come through. Will check on Monday

2024-02-26 09:57 UTC, joshwooding requested changes
We need to add a test here

2024-02-26 09:59 UTC, joshwooding commented
Thanks for raising the PR @stevenmckinnon.

We require all contributors to JPMC projects to complete our Contribution Licence Agreement (CLA). You can sign as an individual or as representing your company. You only need to do this once and it covers all current and future projects managed under our GitHub organization.

The contribution agreement can be found here [JPMC CLA](https://github.com/jpmorganchase/.github/blob/main/jpmc-cla-20230406.md), follow the instructions to complete and return via email.

2024-03-08 09:36 UTC, stevenmckinnon commented
Hey @joshwooding, the CLA is approved now.

2024-03-11 10:17 UTC, joshwooding approved these changes

2024-03-11 15:12 UTC, merged

2024-03-11 15:21 UTC, joshwooding commented
Thanks for the contribution @stevenmckinnon!