Fix tabstrip not collapsing when sharing parent with other items
jpmorganchase/salt-ds pull request #3086
Opened 2024-03-05 14:06 UTC by Fercas123

fixes https://github.com/jpmorganchase/salt-ds/issues/2781

2024-03-05 14:14 UTC, joshwooding requested changes
Is there a way to test this?

2024-03-05 16:54 UTC, origami-z approved these changes

2024-03-07 11:21 UTC, origami-z commented
> There is a regression in touch QA, Looks like the padding left is making the tabstrip think it has enough space to fit the button, and overflow hidden now hides it. One more update to the PR coming up

Maybe QA needs to be updated to include both main type and inline type

2024-03-07 13:18 UTC, origami-z commented
TD of Badge QA should overflow or not?

2024-03-08 09:42 UTC, origami-z approved these changes

2024-03-08 13:33 UTC, lukeac123 approved these changes

2024-03-08 13:34 UTC, merged