left aligned label switch example
jpmorganchase/salt-ds pull request #3150
Opened 2024-03-20 18:40 UTC by libertymayc

playing around to close #3109

One problem with this is the label isn't interactive, clicking it won't change the switch value like having a direct switch label would

2024-03-21 08:55 UTC, joshwooding requested changes
I'm not a fan of these changes, we should find a way to do this without requiring users to add a class.

2024-03-21 14:17 UTC, libertymayc commented
> I'm not a fan of these changes, we should find a way to do this without requiring users to add a class.

me too. are you thinking via a prop? If we use the form field label it will need styling since it's different from the Switch label. as mentioned in the description it also wouldn't have the interaction, plus makes the component itself technically have two labels since Switch is wrapped in one itself

2024-03-21 15:10 UTC, joshwooding commented
> > I'm not a fan of these changes, we should find a way to do this without requiring users to add a class.
> 
> me too. are you thinking via a prop? If we use the form field label it will need styling since it's different from the Switch label. as mentioned in the description it also wouldn't have the interaction, plus it makes the component itself have two labels since Switch is wrapped in one itself 👎

I think the expectation is for it to look different anyway. It's more making sure Switch works with FormField

2024-03-21 17:28 UTC, joshwooding commented on site/src/examples/switch/LeftAlignedLabel.tsx
> +  </>
```suggestion
  <div>
    <FormField labelPlacement="left">
      <FormFieldLabel>Active</FormFieldLabel>
      <Switch />
    </FormField>
  </div>
```

2024-03-21 17:32 UTC, joshwooding commented on site/src/examples/form-field/WithControls.tsx
> +      <FormField>
This example isn't loading?

2024-03-21 18:10 UTC, libertymayc commented on site/src/examples/form-field/WithControls.tsx
> +      <FormField>
fixed

2024-03-22 11:47 UTC, origami-z commented on packages/core/src/switch/Switch.css
> -.saltSwitch-label {
Need this for default switch label

2024-04-24 13:40 UTC, bhoppers2008 submitted a review, later dismissed

2024-04-24 20:19 UTC, origami-z commented on packages/core/src/switch/Switch.css
> +.saltFormField-labelLeft .saltSwitch {
added new

2024-04-25 07:15 UTC, joshwooding approved these changes

2024-04-25 07:16 UTC, joshwooding commented on .changeset/rare-turkeys-change.md
> +Fix padding when Switch used with left/right aligned FormFieldLabel
```suggestion
Fixed padding when a Switch is used with a left/right aligned FormFieldLabel.
```

2024-04-25 07:17 UTC, joshwooding approved these changes

2024-04-25 07:42 UTC, Fercas123 approved these changes

2024-04-25 09:08 UTC, merged