Contact details updates
jpmorganchase/salt-ds pull request #3208
Opened 2024-04-04 14:38 UTC by mikearildbrown

2024-04-05 07:40 UTC, joshwooding commented on site/docs/patterns/contact-details.mdx
> +    src="/img/patterns/contact-details/contact-details-layout-2-list.png"
This src url is broken because the image is incorrectly named

2024-04-05 07:40 UTC, joshwooding requested changes
Left some comments here and in Figma

2024-04-05 14:45 UTC, joshwooding commented
Moved to draft since the images are still a WIP

2024-04-08 16:19 UTC, shey-v approved these changes

2024-04-09 07:29 UTC, joshwooding approved these changes

2024-04-09 07:29 UTC, merged