International phone number updates
jpmorganchase/salt-ds pull request #3243
Opened 2024-04-11 15:38 UTC by mikearildbrown

2024-04-11 16:15 UTC, navkaur76 approved these changes

2024-04-12 06:55 UTC, joshwooding commented on site/docs/patterns/international-phone-number-input.mdx
> +      src: "/img/patterns/international-phone-number-input/IPN-country-dropdown-collapsed.png",
These images jump when toggled

2024-04-12 07:00 UTC, joshwooding requested changes
See comment

2024-04-18 13:46 UTC, joshwooding approved these changes

2024-04-18 13:48 UTC, merged