Data Grid exist alpha and export more internals
jpmorganchase/salt-ds pull request #3256
Opened 2024-04-16 09:40 UTC by origami-z

We need to exist alpha so existing user with "^" dependencies can use up to date / matching version of `@salt-ds/styles` with rest of packages. Otherwise, it needs to be overridden to be `@salt-ds/styles: ^0.2.1`

Export some components to make it possible to produce custom cell editors

2024-06-13 12:24 UTC, joshwooding requested changes
The patchfile also will need to be updated

2024-06-13 13:01 UTC, joshwooding submitted a review, later dismissed

2024-06-19 09:49 UTC, Fercas123 approved these changes

2024-06-19 14:00 UTC, joshwooding approved these changes

2024-06-19 14:58 UTC, merged