[WIP] Breadcrumbs pattern examples
jpmorganchase/salt-ds pull request #3446
Opened 2024-05-21 11:29 UTC by JoanaMMoreira

2024-05-23 15:04 UTC, joshwooding commented on .changeset/khaki-eggs-brake.md
> +Added storybook examples for the breadcrumbs pattern
We don't need a changeset for pattern examples :)

2024-05-23 15:05 UTC, joshwooding commented on packages/core/stories/patterns/breadcrumbs/breadcrumbs.stories.tsx
> +      <ol
ul might be better

2024-05-23 15:11 UTC, joshwooding requested changes

2024-05-23 15:11 UTC, joshwooding commented on packages/core/stories/patterns/breadcrumbs/breadcrumbs.stories.tsx
> +        <MenuButton CascadingMenuProps={{ initialSource }} hideCaret>
This should be swapped to Menu in core

2024-05-29 10:56 UTC, joshwooding requested changes
The site needs to be updated with a link to the examples

2024-05-29 13:09 UTC, joshwooding approved these changes

2024-05-29 13:22 UTC, Fercas123 approved these changes

2024-05-29 13:23 UTC, merged