Stepper input to core
jpmorganchase/salt-ds pull request #3465
Opened 2024-05-24 14:33 UTC by lilyvc

Moves stepper input to core

2024-05-28 12:28 UTC, Fercas123 commented
lgtm, just missing a changeset

2024-05-29 09:28 UTC, joshwooding commented
Moving to draft, to wait for feedback from consumers

2024-06-03 15:06 UTC, Fercas123 submitted a review, later dismissed

2024-06-03 15:54 UTC, ivan-calderon commented
Great job @lilyvc! I'm not sure if I can review components I have not been involved to, but I just wanted to leave a comment about the keyboard navigation if useful. 

Although top-down keyboard arrows allow me to change values as described in the [accessibility tab](https://saltdesignsystem-git-stepper-input-to-core-fed-team.vercel.app/salt/components/stepper-input/accessibility) , I was expecting that the next Tab after the input goes to the up-down buttons as is for the [custom buttons example](https://saltdesignsystem-git-stepper-input-to-core-fed-team.vercel.app/salt/components/stepper-input/examples#custom-buttons). 

If it was meant to work that way please disregard the above and let me know if I can provide the last ✅ for you!

2024-06-03 16:45 UTC, joshwooding commented on site/docs/components/stepper-input/accessibility.mdx
Typically we don't add docs in our promotion to core PRs because it makes them much more work to review. Can we avoid this next time please.

2024-06-03 16:48 UTC, joshwooding commented on site/src/examples/stepper-input/CustomButtons.tsx
> +            aria-label="decerement value"
```suggestion
            aria-label="decrement value"
```

2024-06-03 16:48 UTC, joshwooding commented on packages/core/stories/stepper-input/stepper-input.qa.stories.tsx
> +  title: "Core/Stepper Input/QA",
```suggestion
  title: "Core/Stepper Input/Stepper Input QA",
```

2024-06-03 17:26 UTC, lilyvc commented
> Great job @lilyvc! I'm not sure if I can review components I have not been involved to, but I just wanted to leave a comment about the keyboard navigation if useful.
> 
> Although top-down keyboard arrows allow me to change values as described in the [accessibility tab](https://saltdesignsystem-git-stepper-input-to-core-fed-team.vercel.app/salt/components/stepper-input/accessibility) , I was expecting that the next Tab after the input goes to the up-down buttons as is for the [custom buttons example](https://saltdesignsystem-git-stepper-input-to-core-fed-team.vercel.app/salt/components/stepper-input/examples#custom-buttons).
> 
> If it was meant to work the way it is now, please disregard the above and let me know if I can provide the last ✅ for you!

Thanks for taking a look :) This is a reasonable observation. The default stepper buttons aren't in the tabbing order on purpose because you have the up/down controls, but in the custom button example it would be up to the user and they could configure it either way.

2024-06-04 07:10 UTC, Fercas123 approved these changes

2024-06-04 16:53 UTC, origami-z requested changes
Review `string | number` vs `number`

2024-06-05 08:44 UTC, joshwooding commented on packages/core/src/stepper-input/StepperInput.tsx
>  const withBaseName = makePrefixer("saltStepperInput");
The onChange function here does not follow every other components

2024-06-05 08:44 UTC, joshwooding requested changes
With the onChange and other issues I think we should stop working on this PR and create a new one to address the issues.

2024-07-04 08:16 UTC, joshwooding commented
Closing whilst the other PR is open

2024-07-04 08:16 UTC, closed without merging