Multiselect combobox pill hover
jpmorganchase/salt-ds pull request #3925
Opened 2024-08-02 06:14 UTC by Vineet119

2024-08-02 12:44 UTC, joshwooding commented on packages/core/src/pill-input/PillInput.css
> +.saltPillInput .saltPill {
These changes should be done in Pill.css and only the overrides needed for PillInput should be added here

2024-08-02 12:44 UTC, joshwooding requested changes
see comment

2024-08-05 10:09 UTC, joshwooding submitted a review, later dismissed
The tokens used need to be reviewed

2024-08-06 09:48 UTC, joshwooding submitted a review, later dismissed

2024-08-07 11:11 UTC, joshwooding commented on packages/core/src/pill-input/PillInput.css
> +  border-color: var(--salt-content-foreground-highlight);
```suggestion
  border-color: transparent;
```

2024-08-07 12:47 UTC, yunjungyeh approved these changes

2024-08-07 12:52 UTC, joshwooding approved these changes

2024-08-07 14:07 UTC, merged