Fix `.editable-cell` incorrectly set right text align
jpmorganchase/salt-ds pull request #4145
Opened 2024-09-23 13:55 UTC by origami-z

`.edtiable-cell` should only be setting the border / corner flag styling. `.numeric-cell` is the one for right alignment (for both header and body cells)

#4141

2024-09-23 14:34 UTC, joshwooding submitted a review, later dismissed

2024-09-26 23:01 UTC, joshwooding commented on packages/ag-grid-theme/src/dependencies/dataGridExampleColumns.ts
> +    // This is only here for backwards compatility. Use above 2 classes combination instead.
```suggestion
    // This is only here for backwards compatibility. Use the combination of the above two classes instead.
```

2024-09-26 23:01 UTC, joshwooding commented on .changeset/ninety-bottles-deny.md
> +Fixed `.editable-cell` incorrectly set text align. For numeric columns, use both `.edtiable-cell` and `.numeric-cell` for `cellClass`. Fixes #4141.
```suggestion
Fixed `.editable-cell` incorrectly setting text-align. For numeric columns, use both `.edtiable-cell` and `.numeric-cell` for `cellClass`. Fixes #4141.
```

2024-09-26 23:02 UTC, joshwooding approved these changes

2024-09-26 23:03 UTC, mark-tate approved these changes

2024-09-26 23:17 UTC, joshwooding requested changes
checkbox columns in ag-grid look wider than before

2024-09-27 08:41 UTC, origami-z commented
> checkbox columns in ag-grid look wider than before

they are fine. checkbox column doesn't have fixed size, but being auto resized proportionally. it changed due to number of columns changed.

2024-09-27 09:45 UTC, joshwooding approved these changes

2024-09-27 09:50 UTC, merged