Use Link for emails in contact details pattern
jpmorganchase/salt-ds pull request #4197
Opened 2024-09-27 09:36 UTC by origami-z

#3853

2024-09-27 10:40 UTC, origami-z commented on site/docs/patterns/contact-details.mdx
> +## Changelog
A bit of random idea, should we track change on pattern?

2024-09-27 14:24 UTC, yunjungyeh requested changes

2024-09-30 10:29 UTC, yunjungyeh commented on site/docs/patterns/contact-details.mdx
> +The link function won't be able to be applied in the list version as it is an list item that user select as a whole option from the dropdown.
```suggestion
The link function won't be able to be applied in the list version as it is an list item that users select as a whole option from the dropdown.
```

2024-09-30 12:17 UTC, yunjungyeh commented on site/docs/patterns/contact-details.mdx
> +The link function won't be able to be applied in the list version as it is an list item that user select as a whole option from the dropdown.
updated per feedback from @bhoppers2008

2024-09-30 14:38 UTC, yunjungyeh approved these changes

2024-09-30 15:40 UTC, Fercas123 approved these changes

2024-09-30 16:52 UTC, merged