button bar pattern updates
jpmorganchase/salt-ds pull request #4404
Opened 2024-11-13 13:48 UTC by Fercas123

2024-11-14 08:59 UTC, joshwooding commented on site/public/img/patterns/button-bar/button-bar-anatomy.png
This image doesn't look right? @navkaur76

2024-11-14 08:59 UTC, joshwooding commented on site/docs/patterns/button-bar.mdx
> +### Example 1
I guess the example images haven't been updated yet? @Fercas123

2024-11-14 10:57 UTC, joshwooding commented on site/docs/patterns/button-bar.mdx
> +### Building a Stacked Button Bar
```suggestion
### Building a stacked button bar
```

2024-11-14 12:48 UTC, joshwooding commented on site/docs/patterns/button-bar.mdx
>      src="/img/patterns/button-bar/button-options-example-1.png"
Just a note, these images don't exist

2024-11-20 10:20 UTC, joshwooding requested changes

2024-11-20 10:20 UTC, joshwooding commented on site/public/img/patterns/button-bar/button-bar-anatomy.png
This image is still wrong?

2024-11-20 10:20 UTC, joshwooding commented on site/public/img/patterns/button-bar/button-bar-building-stacked-button-bar-1.png
Was this image exported at the right size?

2024-11-20 10:20 UTC, joshwooding commented on site/public/img/patterns/button-bar/button-bar-building-stacked-button-bar-2.png
Was this image exported at the right size?

2024-11-20 10:20 UTC, joshwooding commented on site/docs/patterns/button-bar.mdx
> +  - You should display transparent actions that aren’t core to the workflow at the opposite end of the button bar.
This doesn't feel equivalent. "secondary actions" are an actual thing "transparent actions" aren't.  "core actions" are used to describe the other type of actions.

2024-11-20 10:20 UTC, joshwooding commented on site/docs/patterns/button-bar.mdx
> +    - The **Submit** solid action uses the solid button.
"solid" action? the opposite is alternate which makes this confusing to me

2024-11-20 10:20 UTC, joshwooding commented on site/docs/patterns/button-bar.mdx
> +  - You should display transparent actions that aren’t core to the workflow at the opposite end of the button bar.
Also secondary action is already used previously.

2024-11-20 10:20 UTC, joshwooding commented on site/docs/patterns/button-bar.mdx
> +There are three button appearances to choose from. Choosing the correct button depends on the context and is ultimately the choice of the application team. For guidance on button choices, please see
```suggestion
There are three button appearances to choose from. Choosing the correct button depends on the context and is ultimately the choice of the application team. For guidance on button choices, please see the [`Button`](/salt/components/button) docs. We recommend using the accented button set for a majority of use cases, alongside the following guidelines for consistent design:
```

2024-11-20 10:21 UTC, origami-z reviewed
Should button bar pattern code in storybook be updated?

2024-11-20 10:21 UTC, origami-z commented on site/public/img/patterns/button-bar/button-bar-building-stacked-button-bar-1.png
needs 2x, image blurred

2024-11-20 10:21 UTC, origami-z commented on site/public/img/patterns/button-bar/button-bar-building-stacked-button-bar-2.png
2x

2024-11-20 10:34 UTC, mark-tate submitted a review, later dismissed

2024-11-20 17:22 UTC, origami-z approved these changes

2024-11-21 09:54 UTC, Fercas123 commented on site/docs/patterns/button-bar.mdx
> +### Example 1
highlighted this on the spec to be looked at and followed up

2024-11-21 09:55 UTC, merged